services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n-datnd:latest
    container_name: n8n-container
    restart: always
    env_file:
      - .env
    environment:
      # === Chuyá»ƒn DB sang Postgres ===
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=your-host
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_USER=your-user
      - DB_POSTGRESDB_PASSWORD=your-password
      - DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false

      - N8N_BINARY_DATA_MODE=s3
      - N8N_S3_BUCKET=your-bucket
      - N8N_S3_REGION=ap-southeast-1
      - N8N_S3_ACCESS_KEY_ID=your-id
      - N8N_S3_SECRET_ACCESS_KEY=your-secret
      - N8N_S3_ENDPOINT=your-endpoint
      - N8N_S3_FORCE_PATH_STYLE=true
      
      - N8N_EXECUTIONS_DATA_PRUNE=true
      - N8N_EXECUTIONS_DATA_MAX_AGE=168           
      - N8N_EXECUTIONS_DATA_PRUNE_MAX_COUNT=5000
      - N8N_EXECUTIONS_DATA_SAVE_ON_DISK=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=true
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - TZ=Asia/Bangkok
      - N8N_HOST=n8n.postiznguyendoandat.click
      - WEBHOOK_URL=https://n8n.postiznguyendoandat.click/

    volumes:
      - n8n_data:/home/node/.n8n           
      - ./files:/data/files                

    networks:
      - n8n_network

  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - n8n
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge

volumes:
  n8n_data:
  caddy_data:
  caddy_config:
